### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by SamerAdra** [kezhenxu94/cache-lite#10]
I found this repo while looking for a lightweight expirable cache in Kotlin. Really appreciate it.
I noticed your latest commit adds generics but it hasn't been released yet. Could you please release a new version to include it?

**Comment by kezhenxu94** [comment]
> I found this repo while looking for a lightweight expirable cache in Kotlin. Really appreciate it.
> I noticed your latest commit adds generics but it hasn't been released yet. Could you please release a new version to include it?

Sure, will release recently

**Comment by kezhenxu94** [comment]
@SamerAdra just release v0.2.0, should be available on maven central (and GitHub package registry) in no time, thanks for using, if you have any further question, please let me know

**Comment by kezhenxu94** [comment]
It should be available now, I'll close this :)
